Input issue
cbgeo-archives/mpm-point-generator pull request #13
Opened 2017-05-26 01:09 UTC by ezrayst

Fixed Krishna's comments.
Rebased

2017-05-26 01:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cb-geo/mpm-point-generator?pullRequest=13) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cb-geo/mpm-point-generator?pullRequest=13) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cb-geo/mpm-point-generator?pullRequest=13) it.</sub>

2017-05-26 02:54 UTC, kks32 requested changes
This has both `input` and `IO` there should be only one! Also  this undoes all my changes, please merge properly or start from the develop branch and then make a new branch. Fix the issues and create a PR.

2017-05-26 02:54 UTC, kks32 commented on include/input.tcc
> -  unsigned vertid = std::numeric_limits<unsigned>::max();
Uninitialised variable

2017-05-26 02:54 UTC, kks32 commented on include/input.tcc
> -  double nvertices = 0, toplines =0;
Why are these removed?

2017-05-26 02:54 UTC, kks32 commented on src/main.cc
> +#include "GMSH.cc"
Can't include implementation files.

2017-05-26 02:55 UTC, kks32 commented
All tests need to pass. I'm closing this PR as this isn't from the develop branch, rebase / merge / checkout from the development branch, and then make your changes.

2017-05-26 03:10 UTC, kks32 reviewed
The code should compile, before you do a PR!

2017-05-26 03:10 UTC, kks32 commented on src/main.cc
> +    std::string output_point = "../bin/vertexcheck.txt";
Don't hard code paths. Why are they in `main`. They should be initialised, if at all, in the `IO` class.

2017-05-26 03:10 UTC, kks32 commented on include/input.h
> -#include <limits>
This is needed.

2017-05-26 03:10 UTC, kks32 commented on include/input.h
>  #include <array>
This entire class is not necessary, move functions to `Mesh` / `GMSH`

2017-05-26 03:10 UTC, kks32 commented on include/input.tcc
> +#include "IO.h"
All these should be in `Mesh` or `GMSH` class

2017-05-26 03:10 UTC, kks32 commented on include/input.tcc
> -    std::vector<std::shared_ptr<Point<Tdim>>> elements_;
All these next 10 lines initialise variables, which are not in your code. These changes were undone. Do not undo others' changes, without sufficient explanation.

2017-05-26 03:10 UTC, kks32 commented on include/input.tcc
> +  //! Element Coordinate and id container
All these overwrites the code, which was initialised, this code doesn't do that. Revert these parts to `develop` version

2017-05-26 03:10 UTC, kks32 commented on include/io.h
> +  //! inputfilename_ is the filename of the input
Just say `input file name`. Do those below as well

2017-05-29 12:43 UTC, kks32 requested changes

2017-05-29 12:43 UTC, kks32 commented on include/gmsh.tcc
> +      outputfile << (0.5 * (0 - (10 * ((3 - point->coordinates().at(1)) * 22))))
Add variables `K0` and `density`

2017-05-29 12:43 UTC, kks32 commented on include/gmsh.tcc
> +    for (unsigned k = 0; k < 4; ++k) {
Declare `4` as a `const` earlier.

2017-05-29 12:43 UTC, kks32 commented on include/input.tcc
> +  double nvertices = 0, toplines = 0;
make `toplines` as `nheaderlines` and `const` with a value of 4.

2017-05-29 12:43 UTC, kks32 commented on include/io.h
> +#include <numeric>
Do you need `numeric`?

2017-05-29 12:43 UTC, kks32 commented on include/io.h
> +  IO(const std::string& pathfile_name) {
This constructor may fail with exceptions.

2017-05-29 12:43 UTC, kks32 commented on include/io.h
> +  IO(const std::string& pathfile_name) {
Single argument constructor must be protected against casting.

2017-05-29 12:43 UTC, kks32 commented on include/io.h
> +    nlohmann::json j;
This should be a member variable.

2017-05-29 12:43 UTC, kks32 commented on include/io.h
> +    pathfile >> j;
Use `json::parse`

2017-05-29 12:43 UTC, kks32 commented on include/io.h
> +  const std::string inputfilename() { return inputfilename_; }
Make all `const` for all 3 functions

2017-05-29 12:43 UTC, kks32 commented on include/mesh.h
> +  virtual void output_vertices(const std::string& outputfilename) = 0;
Make this function return a vector of points. Don't write out here, write it in the IO class.

2017-05-29 12:43 UTC, kks32 commented on include/mesh.h
> +  virtual void output_stresses(const std::string& outputfilename) = 0;
Make this function return a vector of stresses. Don't write out here, write it in the IO class.

2017-05-29 12:43 UTC, kks32 commented on src/main.cc
> +                   "Dimenssion 2 or 3\n";
Fix spelling.

2017-05-29 12:43 UTC, kks32 commented on src/main.cc
> +#include "json.hpp"
Do you need `json` header here?

2017-05-29 12:43 UTC, kks32 commented on src/main.cc
> +    //! Get dimension or Tdim
Dimension is `Tdim`.

2017-05-29 12:43 UTC, kks32 commented on src/main.cc
> +    std::string pathfile_name = argv[1];
Make this `const`

2017-05-29 12:43 UTC, kks32 commented on src/main.cc
> +    mesh->output_vertices(file->outputfilename_point());
The following two functions will pipe results to IO class, which will in turn write the results.

2017-05-29 12:43 UTC, kks32 commented on include/io.h
> +    outputfilename_point_ = j["outputfile_point"].get<std::string>();
What happens if the variables are not declared? Handle exceptions.

2017-05-29 12:43 UTC, kks32 commented on include/gmsh.tcc
> +      outputfile << (0.5 * (0 - (10 * ((3 - point->coordinates().at(1)) * 22))))
Use `K0` and `density` variables

2017-05-29 12:43 UTC, kks32 commented on include/gmsh.tcc
> +  std::array<double, 3> elementarray;
Use a `const` variable to define size of an array.

2017-05-29 12:43 UTC, kks32 commented on include/gmsh.h
>    //! Read from file
Missing constructor.

2017-05-29 12:43 UTC, kks32 commented on include/gmsh.tcc
> +      outputfile << point->coordinates().at(0) << '\t'
Iterate through the coordinates to print out.

2017-05-29 12:43 UTC, kks32 commented on include/input.h
>    std::vector<std::shared_ptr<Point<Tdim>>> read_vertices(
A class needs at least a constructor and a destructor.

2017-05-29 12:49 UTC, kks32 requested changes
Why do we still have `input.h` and `input.tcc` those shouldn't exist, and must have been replaced by the `IO` class.

2017-05-29 17:17 UTC, ezrayst commented on include/io.h
> +  IO(const std::string& pathfile_name) {
Can you elaborate more? I don't quite get it

2017-05-29 18:19 UTC, kks32 requested changes

2017-05-29 18:19 UTC, kks32 commented on include/gmsh.tcc
> +  const unsigned vertex_array_size = 3;
Is this dimension? then use `ndimension`. `vertex_array_size` doesn't mean anything.

2017-05-29 18:19 UTC, kks32 commented on include/gmsh.tcc
> +  const unsigned vertex_array_size = 3;
`ndimension`

2017-05-29 18:19 UTC, kks32 commented on include/gmsh.tcc
> +  double density = 22;
`const`

2017-05-29 18:19 UTC, kks32 commented on include/io.h
> +  IO(const std::string& pathfile_name) {
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#enforcement-89

2017-05-29 18:19 UTC, kks32 commented on include/io.h
> +  const std::string inputfilename() const { return inputfilename_; }
Remove `const` from return type of all 3 functions

2017-05-29 18:19 UTC, kks32 commented on src/main.cc
> +    int Tdim = std::atoi(argv[2]);
should this be `const`? Is it a template argument? why is it named `Tdim`?

2017-05-30 03:29 UTC, ezrayst commented on include/io.h
> +  const std::string inputfilename() const { return inputfilename_; }
so it would be `std::string inputfilename() const { return inputfilename_; }`

2017-05-30 03:32 UTC, ezrayst commented on src/main.cc
> +    int Tdim = std::atoi(argv[2]);
Yes, should be `const`. I am sorry. and yes, it's template, so I used `Tdim` for the name. Do you want `ndimension` as the name?

2017-05-30 11:13 UTC, kks32 requested changes
I don't understand the difference between `points` and `vertices`. It's being used interchangeably in this code.

2017-05-30 11:13 UTC, kks32 commented on bin/pathfile.json
> +	"outputfile_vertex" : "../bin/soilParticles.smf",
Are we writing out vertices?

2017-05-30 11:13 UTC, kks32 commented on include/gmsh.h
> +  unsigned tot_vertices() const { return tot_vertices_; }
Add comments, change `tot_vertices` to `nvertices` to be consistent.

2017-05-30 11:13 UTC, kks32 commented on include/gmsh.h
> +  unsigned tot_vertices_;
change `tot_vertices_` to `nvertices_`

2017-05-30 11:13 UTC, kks32 commented on include/gmsh.h
> +  std::vector<std::shared_ptr<Point<3>>> vertices() const { return vertices_; }
Add comments! `//! Return vertices`

2017-05-30 11:13 UTC, kks32 commented on include/gmsh.h
> +  //! Functions to call private variables
Remove this comment, not useful.

2017-05-30 11:13 UTC, kks32 commented on include/gmsh.h
>    //! Text output
What do you mean by `text output`, comments should be meaningful and describe what the function does.

2017-05-30 11:13 UTC, kks32 commented on include/gmsh.tcc
> +  const double K0 = 0.5;
Naming convention! `K0` should be `k0`.
We have guideline: https://cpp.cb-geo.com/naming/variable_names.html, please follow these guidelines. Reviews are to find any coding errors/bugs, not to check style guidelines. `const` rule in the guideline is only for global variable.

2017-05-30 11:13 UTC, kks32 commented on include/gmsh.tcc
> +                     (0 - (10 * ((3 - point->coordinates().at(1)) * density))))
What's `10`?

2017-05-30 11:13 UTC, kks32 commented on include/io.h
> +#include <mesh.h>
These are not `std` includes, and are local includes, use `"mesh.h"` instead `<mesh.h>`

2017-05-30 11:13 UTC, kks32 commented on include/io.h
> +      std::cout << "Caught exception: " << except.what() << '\n'
If you want to `catch` exceptions here, then set default paths for the member variables.

2017-05-30 11:13 UTC, kks32 commented on include/io.h
> +      const std::vector<std::shared_ptr<Point<3>>> vertices,
Why is this not passed by reference?

2017-05-30 11:13 UTC, kks32 commented on include/io.h
> +      const unsigned& tot_points);
This should be pass by value not `const&`. See: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-in

2017-05-30 11:13 UTC, kks32 commented on include/io.h
>    //! return output file name for point
`point` or `vertex`?

2017-05-30 11:13 UTC, kks32 commented on include/io.h
> +  //! filename of the output for point
`point` or `vertex`?

2017-05-30 11:13 UTC, kks32 commented on include/io.tcc
> +#include "io.h"
Should not include `io.h`.

2017-05-30 11:13 UTC, kks32 commented on include/io.tcc
> +void write_output_vertices(
This is defined as a global function, how does it know it is for `IO` class member function?

2017-05-30 11:13 UTC, kks32 commented on include/io.tcc
> +    const unsigned tot_vertices) {
Function definition in `io.h` doesn't match `io.tcc`

2017-05-30 11:13 UTC, kks32 commented on include/io.tcc
> +      outputfile << point->coordinates().at(0) << '\t'
Use an iterator.

2017-05-30 11:13 UTC, kks32 commented on include/io.tcc
> +  std::cout << "The output file for soil particles has been generated."
Use new line at the end of this line.

2017-05-30 11:13 UTC, kks32 commented on include/io.tcc
> +  std::cout << "success\n";
Shouldn't this be writing stresses?

2017-05-30 11:13 UTC, kks32 commented on src/main.cc
> +#include <vector>
Where do you need `std::vector`?

2017-05-31 06:22 UTC, ezrayst commented on include/gmsh.h
>    //! Text output
It was not from me, but I will change it.

2017-05-31 06:27 UTC, ezrayst commented on include/gmsh.tcc
> +                     (0 - (10 * ((3 - point->coordinates().at(1)) * density))))
I haven't changed this part. Let's deal with it in `stress issue`?

2017-05-31 06:31 UTC, ezrayst commented on include/io.tcc
> +  std::cout << "The output file for soil particles has been generated."
I have it, it's shown in the next line

2017-05-31 06:32 UTC, ezrayst commented on include/io.tcc
> +  std::cout << "success\n";
I haven't done it, since there are problems with the stress so far.

2017-05-31 06:49 UTC, ezrayst commented on include/io.h
> +      const std::vector<std::shared_ptr<Point<3>>> vertices,
I have typo actually. My bad! It's different in `.tcc` and in `.h`

2017-05-31 06:51 UTC, ezrayst commented on include/gmsh.h
>    //! Text output
This was there, and I haven't changed it yet. Let me, the next time I come across anything, I will fix it

2017-05-31 10:10 UTC, kks32 requested changes

2017-05-31 10:10 UTC, kks32 commented on include/io.h
> +#include "gmsh.h"
`gmsh.h` is a derived class, this shouldn't be included.

2017-05-31 10:10 UTC, kks32 commented on include/io.h
> +                           const unsigned tot_points);
just `unsigned`

2017-05-31 10:10 UTC, kks32 commented on include/io.h
> +      const unsigned tot_points);
remove `const`

2017-05-31 10:10 UTC, kks32 commented on include/io.h
> +      const unsigned tot_points);
Rename to `nvertices`.

2017-05-31 10:10 UTC, kks32 commented on include/io.h
> +                           const unsigned tot_points);
Rename to `nvertices`

2017-05-31 10:10 UTC, kks32 commented on include/io.tcc
> +void IO::write_output_vertices(
Input parameters should be described in the function.

2017-05-31 10:10 UTC, kks32 commented on include/io.h
> +      const std::string& outputfilename,
why does `IO` class need this? This is in the private variable.

2017-05-31 10:10 UTC, kks32 commented on include/io.h
> +  void write_output_stress(const std::string& outputfilename,
No need to pass `outputfilename`, this is a member variable of the `IO` class

2017-05-31 10:10 UTC, kks32 commented on include/io.h
> +  //! \brief Get the private properties
Do we need any of these output filename functions?

2017-05-31 10:10 UTC, kks32 commented on include/io.tcc
> +#include <fstream>
This is a template implementation, no need to have includes. These are part of a header file, which already has those includes.

2017-05-31 10:10 UTC, kks32 commented on include/io.tcc
> +  //! Open file to write output
`clang-format`

2017-05-31 10:10 UTC, kks32 commented on include/io.tcc
> +    const unsigned tot_vertices) {
remove `const` and rename to `nvertices`

2017-05-31 10:10 UTC, kks32 commented on include/io.tcc
> +  std::cout << "The output file for soil particles has been generated."
Yes, merge it to a single line.

2017-05-31 10:10 UTC, kks32 commented on include/io.tcc
> +    const unsigned tot_points) {
remove `const` and rename to `npoints`

2017-05-31 10:10 UTC, kks32 commented on include/mesh.h
> +  virtual void output_stresses(const std::string& outputfilename) = 0;
Shouldn't need the file name. Shouldn't it be returning a vector?

2017-05-31 10:10 UTC, kks32 commented on src/main.cc
> +      std::cout << "Usage: ./mpm-point-generator /path/to/path_file.txt\n"
`.txt` file? Shouldn't this be a `.json` file?

2017-05-31 10:10 UTC, kks32 commented on src/main.cc
> +    const std::string pathfile_name = argv[1];
rename to `inputfile`

2017-05-31 17:52 UTC, ezrayst commented on include/io.h
> +  //! \brief Get the private properties
Not if we deal everything right now in `io`

2017-05-31 17:54 UTC, kks32 commented on include/io.h
> +  //! \brief Get the private properties
Remove these functions.

2017-05-31 17:56 UTC, ezrayst commented on src/main.cc
> +    const std::string pathfile_name = argv[1];
it would be quite confusing with the real `inputfile` right?

2017-05-31 18:01 UTC, kks32 commented on src/main.cc
> +    const std::string pathfile_name = argv[1];
You don't need the variable `pathfile_name`, remove it altogether and use `argv` directly.

2017-05-31 18:07 UTC, kks32 requested changes

2017-05-31 18:07 UTC, kks32 commented on src/main.cc
>      if (argc != 3) {
we no longer need the dimension of the problem in `main`. Remove dimension argument.

2017-05-31 18:07 UTC, kks32 commented on src/main.cc
> +    const unsigned ndimension = std::atoi(argv[2]);
Unused variable. Remove `ndimension`.

2017-05-31 18:07 UTC, kks32 commented on src/main.cc
> +    file->write_output_vertices(file->outputfilename_vertex(), mesh->vertices(),
No need to pass `outputfilename_vertex()`

2017-05-31 21:29 UTC, kks32 approved these changes

2017-05-31 21:36 UTC, merged