Test class
cbgeo-archives/mpm-point-generator pull request #16
Opened 2017-06-01 18:55 UTC by ezrayst

For 2D and 3D `point`

2017-06-01 19:30 UTC, kks32 requested changes
You need to check for maximum and minimum possible values and values of zero (3 cases) for 2D and 3D.

2017-06-01 19:30 UTC, kks32 commented on tests/point_test.cc
> +
Remove white space

2017-06-01 19:30 UTC, kks32 commented on tests/point_test.cc
> +//! \details Write arbritrary index and coordinate and store them
Remove this line.

2017-06-01 19:30 UTC, kks32 commented on tests/point_test.cc
> +//! \brief Check that Point will store right values
`Check Point class`

2017-06-01 19:30 UTC, kks32 commented on tests/point_test.cc
> +  const unsigned Tdim_3d = 3;
rename to `DIM`

2017-06-01 19:30 UTC, kks32 commented on tests/point_test.cc
> +  unsigned index_3d = 0;
rename to `index`

2017-06-01 19:30 UTC, kks32 commented on tests/point_test.cc
> +  REQUIRE(node_3d->coordinates().at(0) == 0);
This is a double you need a tolerance.

2017-06-01 19:30 UTC, kks32 commented on tests/point_test.cc
> +  const unsigned Tdim_2d = 2;
Have a separate test function for 2D.

2017-06-01 22:05 UTC, kks32 requested changes

2017-06-01 22:05 UTC, kks32 commented on tests/point_test_2d.cc
> +// Point test
You don't need 2 different files, you can have them in the same file.

2017-06-01 22:05 UTC, kks32 commented on tests/point_test_2d.cc
> +#include <cmath>
`cmath` should be separate. You don't need this.

2017-06-01 22:05 UTC, kks32 commented on tests/point_test_2d.cc
> +  const double tol = pow(10, -12);
be consistent with naming. Use `1E-16`. Don't use `pow`.

2017-06-01 22:05 UTC, kks32 commented on tests/point_test_2d.cc
> +  index = 4294967295;
Use `limits` to define min, max ranges, don't use actual numbers.

2017-06-01 22:10 UTC, ezrayst commented on tests/point_test_2d.cc
> +// Point test
do you want two `sections`? or just one?

2017-06-01 22:11 UTC, kks32 commented on tests/point_test_2d.cc
> +// Point test
Yes, 2 sections.

2017-06-02 00:42 UTC, kks32 commented
refer to the issue number you are trying to fix when creating a PR.

2017-06-02 12:38 UTC, kks32 requested changes
Split test cases for 2D/3D.

2017-06-02 12:38 UTC, kks32 commented on tests/point_test.cc
> +TEST_CASE("Point base is checked in 2D and 3D", "[Point][2D][3D]") {
Can we have a test case for 2D separate from 3D?

2017-06-07 09:54 UTC, kks32 requested changes

2017-06-07 09:54 UTC, kks32 commented on tests/point_test.cc
> +  const double tol = 1.E-12;
Rename to `tolerance`

2017-06-07 09:54 UTC, kks32 commented on tests/point_test.cc
> +  SECTION("2D test at zeros") {
2D test of what? `Coordinates are checked for zero values`.

2017-06-07 09:54 UTC, kks32 commented on tests/point_test.cc
> +    unsigned index = 0;
`const` index and coordinates.

2017-06-07 09:54 UTC, kks32 commented on tests/point_test.cc
> +  SECTION("2D test at minimum limits") {
`Coordinates are checked for minimum values`.

2017-06-07 09:54 UTC, kks32 commented on tests/point_test.cc
> +    unsigned index = std::numeric_limits<unsigned>::min();
`const`

2017-06-07 09:54 UTC, kks32 commented on tests/point_test.cc
> +  SECTION("2D test at zeros") {
`Coordinates are checked for maximum values`.

2017-06-07 09:54 UTC, kks32 commented on tests/point_test.cc
> +  const double tol = 1.E-12;
`tolerance`

2017-06-07 09:54 UTC, kks32 commented on tests/point_test.cc
> +    unsigned index = 0;
const

2017-06-07 09:54 UTC, kks32 commented on tests/point_test.cc
> +  SECTION("3D test at maximum limits") {
Here you are starting with the maximum, why? be consistent with 2D.

2017-06-07 09:54 UTC, kks32 commented on tests/point_test.cc
> +  SECTION("3D test at zeros") {
Rename sections similar to 2D.

2017-06-07 19:38 UTC, kks32 approved these changes

2017-06-07 19:38 UTC, merged