Stress issue
cbgeo-archives/mpm-point-generator pull request #17
Opened 2017-06-01 23:27 UTC by ezrayst

change `point` class
change `gmsh.tcc` structure a little

2017-06-02 00:20 UTC, kks32 requested changes
@ezrayst You might want to revert most of your changes.

2017-06-02 00:20 UTC, kks32 commented on include/gmsh.h
> +  //! Make vector of point class
Change to `Generate a vector of material points`

2017-06-02 00:20 UTC, kks32 commented on include/gmsh.h
>    //! Compute stresses
Class needs a constructor.

2017-06-02 00:20 UTC, kks32 commented on include/gmsh.h
> +  //! Vector of id
Change to `vector of vertex ids`

2017-06-02 00:20 UTC, kks32 commented on include/gmsh.h
> +  //! Vector of vertices
If I have vertices, why do I need a vector of vertex ids and `coord_`s separately?

2017-06-02 00:20 UTC, kks32 commented on include/gmsh.tcc
> +        istream >> coord.at(0) >> coord.at(1) >> coord.at(2);
This is the vertex, why is it being replaced by coord?

2017-06-02 00:20 UTC, kks32 commented on include/gmsh.tcc
>    double density = 22;
`const`.

2017-06-02 00:20 UTC, kks32 commented on include/gmsh.tcc
> +        // if (elementtype != ndimension) {
Why is this being commented out?

2017-06-02 00:20 UTC, kks32 commented on include/io.h
> +    vertices_filename_ = "../bin/material_points.txt";
No! What happens if I run the code in the root directory? Never do this.

2017-06-02 00:20 UTC, kks32 commented on include/io.h
> -  void write_stresses(const std::vector<std::array<double, 6>>& stresses);
Write stresses should get a vector of stresses, not vertices.

2017-06-02 00:23 UTC, kks32 commented on include/gmsh.tcc
> +    stress_.push_back(stress);
Why was this reverted back to `push_back` from `emplace_back`?

2017-06-02 00:24 UTC, kks32 requested changes

2017-06-02 00:24 UTC, kks32 commented on include/gmsh.tcc
> +    vertices_.emplace_back(
Is this just so that you can add `stresses` to points?

2017-06-02 00:33 UTC, kks32 requested changes

2017-06-02 00:33 UTC, kks32 commented on include/gmsh.tcc
> +  for (const auto& point : coords_) {
Only change required is this, when you find the stress, assign stress to the right material point.

2017-06-02 00:33 UTC, kks32 commented on include/gmsh.tcc
> +  const unsigned ndimension = 3;
Why is the dimension defined here? It should be a global variable, and possibly a template argument.

2017-06-02 00:33 UTC, kks32 commented on src/main.cc
> +    io->write_stresses(mesh->vertices());
you can't return all the vertices, when all you need is stresses.

2017-06-02 00:41 UTC, kks32 requested changes
Create a vector of `vertices` and a vector of `elements` in the mesh class. If you want to use `Point` to store MPM points.

2017-06-02 00:41 UTC, kks32 commented on include/io.tcc
> +    const std::vector<std::shared_ptr<Point<3>>>& vertices) {
If you are changing function arguments, you need to change the comments! Anyway, this should a vector of stresses.

2017-06-02 00:41 UTC, kks32 commented on include/point.h
> +  Point(unsigned id, const std::array<double, Tdim>& coord,
Not all points have stresses, like a vertex. You can derive a material point class.

2017-06-02 00:41 UTC, kks32 commented on include/point.h
> +  std::array<double, 6> stress() const { return stress_; }
You need the point class to hold the vertex info, or is it being done in the Mesh class?

2017-06-02 07:21 UTC, ezrayst commented on include/gmsh.tcc
> +        // if (elementtype != ndimension) {
I need to generate the stress to construct `point`. Let me just comment it out first then I will come back to the `elements`

2017-06-02 07:24 UTC, ezrayst commented on include/io.h
> +    vertices_filename_ = "../bin/material_points.txt";
Then, do I need to add the feature of the directory for the output files?

2017-06-02 07:35 UTC, ezrayst commented on include/gmsh.tcc
> +    stress_.push_back(stress);
I think the better way is to make `stress` inside `emplace_back`. What do you think?

2017-06-02 07:52 UTC, ezrayst commented on include/gmsh.tcc
> +  const unsigned ndimension = 3;
The code currently used it this way. It will be changed to a template argument later

2017-06-02 07:56 UTC, ezrayst commented on src/main.cc
> +    io->write_stresses(mesh->vertices());
In this case `vertices` are `point class` with `stress` stored inside them

2017-06-02 07:57 UTC, ezrayst commented on include/gmsh.tcc
> +    vertices_.emplace_back(
Yes! I designed the constructor of `points` to contain `id`, `coord`, and `stress`.

2017-06-02 10:36 UTC, kks32 commented on include/gmsh.tcc
> +        // if (elementtype != ndimension) {
Elements have nothing to do with points. Vertices and points are not interchangable.

2017-06-07 06:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cb-geo/mpm-point-generator?pullRequest=17) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cb-geo/mpm-point-generator?pullRequest=17) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: ezrayst<br/>:x: cw646<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cb-geo/mpm-point-generator?pullRequest=17) it.</sub>

2017-06-16 10:47 UTC, closed without merging