Points within element issues #14, #18, #19
cbgeo-archives/mpm-point-generator pull request #21
Opened 2017-06-09 14:46 UTC by cw646

New pull request, removes Eigen files.

2017-06-09 14:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cb-geo/mpm-point-generator?pullRequest=21) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cb-geo/mpm-point-generator?pullRequest=21) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: ezrayst<br/>:x: cw646<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cb-geo/mpm-point-generator?pullRequest=21) it.</sub>

2017-06-09 15:11 UTC, kks32 requested changes

2017-06-09 15:11 UTC, kks32 commented on include/gmsh.h
> +#include "mesh.h"
These local include files should be at the end after `Eigen` includes

2017-06-09 15:11 UTC, kks32 commented on include/gmsh.h
> +  std::map<double, std::array<double, 4>> elements() const { return elements_; }
IDs should be unsigned or int.

2017-06-09 15:11 UTC, kks32 commented on include/gmsh.h
>  class GMSH : public Mesh {
Make class templatise with dimension. This avoids defining dimension elsewhere within GMSH

2017-06-09 15:11 UTC, kks32 commented on include/gmsh.h
> +  std::map<double, std::array<double, 4>> elements() const { return elements_; }
Is the number `4` fixed for all elements?

2017-06-09 15:11 UTC, kks32 commented on include/gmsh.h
> +  std::vector<std::shared_ptr<Point<3>>> materialpoints_;
This should be from the template argument of dimension `Tdim`

2017-06-09 15:11 UTC, kks32 commented on include/gmsh.h
> +  std::map<double, std::array<double, 4>> elements_;
Change it to a map of unsigned to a vector of unsigned.

2017-06-09 15:11 UTC, kks32 commented on include/gmsh.h
> +  std::map<double, std::array<double, 12>> elementcoordinates_;
These coordinates are vertices coords, right?

2017-06-09 15:11 UTC, kks32 commented on include/gmsh.tcc
>    const unsigned ndimension = 3;
Use the template dimnsion.

2017-06-09 15:11 UTC, kks32 commented on include/gmsh.tcc
> +  const unsigned element_type = 4;
Use an ENUM

2017-06-09 15:11 UTC, kks32 commented on include/gmsh.tcc
> +  for (unsigned q = firstelement; q <= lastelement; ++q) {
I thought ezra's latest commit fixed this algorithm

2017-06-09 15:11 UTC, kks32 commented on include/gmsh.tcc
> +  for (unsigned q = firstelement; q <= lastelement; ++q) {
```
+      //! Iterate through the 4 vertices to get coordinates
+      for (unsigned q = 0; q <= 3; ++q) {
+        //! Get the vertex wanted from the id 
+        verticesfind = vertices_.find(elementkeyvalues[q]);
+        //! For each vertex, store the coordinates
+        //! j = 0 -> [X], j = 0 -> [Y], j = 0 -> [Z]
+        for (unsigned j = 0; j <= 2; ++j) {
+          verticesarray[q * 3 + j] = verticesfind->second[j];
         }
       }
```

2017-06-09 15:11 UTC, kks32 commented on include/gmsh.tcc
> +      //++++++++++++++++++++++++++++++++++++++
Can you iterate here as well?

2017-06-09 15:11 UTC, kks32 commented on include/gmsh.tcc
> +      for (unsigned i = 0; i <= 3; ++i) {
Why do they have different indices 3 and 2?

2017-06-09 16:53 UTC, kks32 requested changes

2017-06-09 16:53 UTC, kks32 commented on include/gmsh.h
>  // libraries
You don't need to explicity say local or libraries.

2017-06-09 16:53 UTC, kks32 commented on include/gmsh.h
> +template <unsigned Tdim, unsigned Tvert, unsigned Tncoords>
You don't need `Tncoords` use the product of Tdim * Tvertices.

2017-06-09 16:53 UTC, kks32 commented on include/gmsh.h
> +template <unsigned Tdim, unsigned Tvert, unsigned Tncoords>
Rename `Tvert` as `Tvertices`

2017-06-09 16:53 UTC, kks32 commented on include/gmsh.h
> +  //! Number of vertices in total
//! Total number of vertices

2017-06-09 16:53 UTC, kks32 commented on include/gmsh.tcc
> +  std::array<double, Tvert> elementarray;
Change `double` to `int` or `unsigned` for all ids

2017-06-09 16:53 UTC, kks32 commented on include/gmsh.tcc
>    double density = 22;
These should be const

2017-06-09 16:53 UTC, kks32 commented on src/main.cc
> +    std::unique_ptr<GMSH<3, 4, 12>> mesh(new GMSH<3, 4, 12>());
This should be a `Mesh` class object, not `GMSH`

2017-06-09 19:04 UTC, ezrayst commented on include/gmsh.tcc
> +  const unsigned element_type = 4;
I will use `Tvertices` instead

2017-06-10 10:38 UTC, kks32 requested changes
Check inheritance and base class / derived class of Mesh and GMSH.

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.tcc
> +//! \Param[in] Tdim = Dimension, Tvert = n vertices in element
Please read the Doxygen style for variables.
`\tparam Tdim Dimension`

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.tcc
> +//! \Param[in] Tdim = Dimension, Tvert = n vertices in element
`\tparam`

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.tcc
> +        //! \details If element type not == to specified Tvertices, skip
No `\details` inside the function!

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.tcc
> +  GMSH::store_element_vertices();
use `this->`

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.tcc
> +//! \Param[in] Tdim = Dimension, Tvert = n vertices in element
Remove `=` and should be `\tparam`

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.tcc
> +      for (unsigned j = 0; j < 4; ++j) {
Can we not combine these two for loops? Shouldn't this be iterating to Tvertices?

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.tcc
> +  typename std::map<unsigned, std::array<double, Tdim * Tvertices>>::iterator
Use `alias`

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.tcc
> +  for (unsigned t = firstelementcoord; t < lastelementcoord + 1; ++t) {
Why not use an iterator?

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.tcc
> +  for (unsigned i = firstelement; i <= lastelement; ++i) {
Use an iterator.

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.tcc
> +      for (unsigned i = 0; i < 3; ++i) {
i < Tdim, j < Tvertices

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.tcc
> +  const unsigned stress_comp = 6;
This is just Tdim * 2, use Tdim * 2 instead.

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.tcc
> +  std::cout << "Initial stresses for material points computed.\n";
Remove cout

2017-06-10 10:38 UTC, kks32 commented on include/io.tcc
>    std::fstream vertices_file;
Change vertices to material points everywher.

2017-06-10 10:38 UTC, kks32 commented on include/mesh.h
> +  //! \brief constructor for a mesh class
Remove these!

2017-06-10 10:38 UTC, kks32 commented on include/mesh.h
> +  virtual std::vector<std::shared_ptr<Point<Tdim>>> material_points() {
Why are these virtual?

2017-06-10 10:38 UTC, kks32 commented on include/mesh.h
> +  virtual std::map<unsigned, std::array<double, Tdim>> vertices() const {
Shouldn't be virtual

2017-06-10 10:38 UTC, kks32 commented on include/mesh.h
> +  virtual std::map<unsigned, std::array<double, Tvertices>> elements() const {
Not virutal

2017-06-10 10:38 UTC, kks32 commented on include/mesh.h
> +  virtual std::vector<std::array<double, 6>> stress() const {
Not virutal

2017-06-10 10:38 UTC, kks32 commented on include/mesh.h
> +  std::vector<std::shared_ptr<Point<Tdim>>> materialpoints_;
Add comment

2017-06-10 10:38 UTC, kks32 commented on include/mesh.h
> +  std::vector<std::array<double, 6>> stress_;
Should be Tdim * 2

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.h
> +  std::vector<std::array<double, 6>> stress() const {
Should be defined in `Mesh`

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.h
> +  std::map<unsigned, std::array<double, Tvertices>> elements() const {
Should be defined in `Mesh`

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.h
> +  std::map<unsigned, std::array<double, Tdim>> vertices() const {
Should be defined in `Mesh`

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.h
> +  std::vector<std::shared_ptr<Point<Tdim>>> material_points() {
Should be defined in Mesh

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.h
> +  unsigned nvertices() const { return Mesh<Tdim, Tvertices>::nvertices_; }
Should be defined in Mesh

2017-06-10 10:38 UTC, kks32 commented on include/gmsh.h
> +  std::vector<std::array<double, 6>> stress() const {
Use the Mesh class's `stress_`.  using `Mesh<Tdim, Tvertices>::stress_`

2017-06-10 10:38 UTC, kks32 commented on src/main.cc
> +    //! \Param[in] Tdim = Dimension, Tvert = n vertices in element
Why `\Param` in the middle of the main function?

2017-06-10 10:38 UTC, kks32 commented on src/main.cc
> +    GMSH<3, 4> gmsh;
GMSH should not appear!

2017-06-10 10:38 UTC, kks32 commented on src/main.cc
> +    Mesh<3, 4>* mesh = &gmsh;
Use a unique_ptr of base class `Mesh` but create it with a new `GMSH`

2017-06-10 10:38 UTC, kks32 commented on src/main.cc
> +    io->write_vertices(mesh->material_points());
should be `write_material_points`

2017-06-11 11:12 UTC, kks32 requested changes

2017-06-11 11:12 UTC, kks32 commented on include/gmsh.tcc
> +        Mesh<Tdim, Tvertices>::vertices_.insert(std::make_pair(vertid, vertex));
Use `using Mesh<Tdim, Tvertices>::vertices_` in the header file, and you can use `vertices_`.

2017-06-12 17:51 UTC, kks32 requested changes

2017-06-12 17:51 UTC, kks32 commented on include/gmsh.tcc
> +//! \tparam Tdim Dimension, Tvert Number of vertices in element
`Tvert` should be in the next line. Use `doxygen` to check if the comments are generated properly.

2017-06-12 17:51 UTC, kks32 commented on include/gmsh.tcc
> +//! \tparam Tdim Dimension, Tvert Number of vertices in element
Same `Tvert` in a new line

2017-06-13 10:34 UTC, kks32 requested changes

2017-06-13 10:34 UTC, kks32 commented on include/gmsh.h
> +  //! Return a map of mesh element vertices
This should be in the `Mesh` class

2017-06-13 10:34 UTC, kks32 commented on include/gmsh.h
> +class GMSH : public Mesh<Tdim> {
Templatise the mesh with `Tvertices` as well.

2017-06-13 10:34 UTC, kks32 commented on include/gmsh.h
> +  std::map<unsigned, std::array<unsigned, Tvertices>> elements() const {
This should go to the `Mesh` class

2017-06-13 10:34 UTC, kks32 commented on include/gmsh.h
> +  //! Number of vertices in total
`//! Total number of vertices`

2017-06-13 10:34 UTC, kks32 commented on include/gmsh.h
> +  //! Stress vector in Voigt Notation
`stress_`, `vertices_`, and `elementcoords_` should be in base class `Mesh`.

2017-06-13 10:34 UTC, kks32 commented on include/gmsh.h
> +  std::map<double, std::array<double, Tdim * Tvertices>> elementcoordinates_;
Why coordinates of elements, is it not sufficient to map it to the ID of vertices?

2017-06-13 10:34 UTC, kks32 commented on include/gmsh.tcc
> +        elementkeyvalues[j] = elementfind->second[j];
Use `.at` operator

2017-06-13 10:34 UTC, kks32 commented on include/gmsh.tcc
> +      for (unsigned q = 0; q < Tvertices; ++q) {
Which `q`, defined in line 146 or 155?

2017-06-13 10:34 UTC, kks32 commented on include/gmsh.tcc
> +        pointsarray[i] = 0;
Use STL algorithms or fill

2017-06-13 10:34 UTC, kks32 commented on include/gmsh.tcc
> +        pointsarray[i] = 0;
Why not declare pointsarray here?

2017-06-13 10:34 UTC, kks32 commented on include/gmsh.tcc
> +  for (const auto& point : Mesh<Tdim>::materialpoints_) {
Use `using` in the derived class to avoid these `Mesh<Tdim>::`

2017-06-13 10:34 UTC, kks32 commented on include/io.tcc
> +    // Stress needs ID too
OK!

2017-06-13 10:34 UTC, kks32 commented on include/mesh.h
> +  std::vector<std::shared_ptr<Point<Tdim>>> write_material_points() {
rename to `material_points` as this function doesn't write anything.

2017-06-13 10:34 UTC, kks32 commented on include/mesh.h
> +  //! Container for storing material points
Shouldn't these be in `protected`?

2017-06-14 07:48 UTC, kks32 requested changes

2017-06-14 07:48 UTC, kks32 commented on include/gmsh.h
Could you run `clang-format`, the includes are not in the right order.

2017-06-15 09:56 UTC, kks32 requested changes

2017-06-15 09:56 UTC, kks32 commented on src/main.cc
>      mesh->read_vertices(io->mesh_file_name());
Could we have a single function? `read_mesh` which calls both the vertices and elements?

2017-06-16 10:38 UTC, kks32 approved these changes

2017-06-16 10:49 UTC, merged