:art: fix issue #22, and fix test cases
cbgeo-archives/mpm-point-generator pull request #23
Opened 2017-06-19 21:31 UTC by ezrayst

2017-06-20 09:18 UTC, kks32 requested changes

2017-06-20 09:18 UTC, kks32 commented on include/gmsh.h
> -  //! Compute stresses
Why is compute stress function removed?

2017-06-20 09:18 UTC, kks32 commented on include/gmsh.tcc
> +  // Material density
Please separate create material points from the stress computation.

2017-06-20 09:18 UTC, kks32 commented on include/io.h
> -      const std::vector<std::array<double, Tdim * 2>>& stresses);
Write stresses should only need a vector of doubles, not a shared pointer.

2017-06-20 09:18 UTC, kks32 commented on include/mesh.h
> -  //! Compute initial stresses for material points
This is required. Compute stress should be a separate function.

2017-06-20 09:18 UTC, kks32 commented on include/point.h
> -  Point(unsigned id, const std::array<double, Tdim>& coord) : id_{id} {
Constructor with just ID and coordinates.

2017-06-20 09:18 UTC, kks32 commented on include/point.h
> +    stress_ = stress;
Stress should be initialised later.

2017-06-20 09:18 UTC, kks32 commented on tests/point_test.cc
> +    const std::array<double, DIM * 2> stress{0, 0, 0, 0};
This should be computed to verify, not assign and verify.

2017-06-20 18:34 UTC, ezrayst commented on include/io.h
> -      const std::vector<std::array<double, Tdim * 2>>& stresses);
In the next push, I will still have `materialpoints` as the input. Please let me know how to change them

2017-06-20 18:34 UTC, ezrayst commented on include/io.h
> -      const std::vector<std::array<double, Tdim * 2>>& stresses);
Also, you don't want `stress` in `mesh` anymore?

2017-06-20 19:15 UTC, kks32 requested changes

2017-06-20 19:15 UTC, kks32 commented on include/io.h
> -      const std::vector<std::array<double, Tdim * 2>>& stresses);
No, I don't want `stress` in `mesh`, stress is a property of `material_point`

2017-06-20 19:15 UTC, kks32 commented on include/io.tcc
> +    const std::vector<std::shared_ptr<Point<Tdim>>>& materialpoints) {
Iterate over `materialpoints` create a vector of stresses and pass it to this function.

2017-06-20 19:15 UTC, kks32 commented on include/point.h
> -  Point(unsigned id, const std::array<double, Tdim>& coord) : id_{id} {
Revert to `Point(unsigned id, const std::array<double, Tdim>& coord) : id_{id} {`

2017-06-20 19:15 UTC, kks32 commented on include/point.h
> +  //! Set stress
`//! Assign stresses`.

2017-06-20 19:15 UTC, kks32 commented on include/point.h
> +  void set_stress(const std::array<double, Tdim * 2>& stress) {
Overload this function call it `stress`

2017-06-20 19:28 UTC, ezrayst commented on include/io.tcc
> +    const std::vector<std::shared_ptr<Point<Tdim>>>& materialpoints) {
do you want to make a new function in `io` to iterate?

2017-06-21 09:46 UTC, kks32 approved these changes

2017-06-21 09:46 UTC, merged