refactor output_stress
cbgeo-archives/mpm-point-generator pull request #8
Opened 2017-05-25 02:02 UTC by ezrayst

I have made `initStress.h` as a new class system.
I assumed the maximum y-coord is constant throughout.

2017-05-25 02:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cb-geo/mpm-point-generator?pullRequest=8) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cb-geo/mpm-point-generator?pullRequest=8) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cb-geo/mpm-point-generator?pullRequest=8) it.</sub>

2017-05-25 10:17 UTC, kks32 requested changes
Why do we need a new class for stresses, why can't the material points have stresses?

Please stick to naming conventions.

2017-05-25 10:17 UTC, kks32 commented on include/GMSH.cc
> +  double ver_stress;
You are not using this until later. Declare when you use them.

2017-05-25 10:17 UTC, kks32 commented on include/GMSH.cc
> +  std::vector<double> ycoord;
Plural, ycoordinates. (why `y` rename to vertical)

2017-05-25 10:17 UTC, kks32 commented on include/GMSH.cc
> +  double max_height = *std::max_element(ycoord.begin(), ycoord.end());
Why is there a `*`

2017-05-25 10:17 UTC, kks32 commented on include/GMSH.cc
>    const std::string outputfilename = "stresscheck.txt";
Output files shouldn't be hardcoded, should be called from the `IO` class.

2017-05-25 10:17 UTC, kks32 commented on include/GMSH.cc
>    std::fstream stresscheck;
Rename `stresscheck` it's not checking anything.

2017-05-25 10:17 UTC, kks32 commented on include/GMSH.cc
> +    for (auto const& point : stresses_) {
`const auto&`

2017-05-25 10:17 UTC, kks32 commented on include/GMSH.h
> +#include "initStress.h"
Naming convention. All lower case

2017-05-25 10:17 UTC, kks32 commented on include/initStress.h
> +#ifndef INITSTRESS_H
Remove this class, use `stress` in `material_points`

2017-05-25 10:17 UTC, kks32 commented
We also need you to rebase to the `develop` so you have all the integrations and tests as passing.

2017-05-25 10:27 UTC, cw646 commented on include/GMSH.cc
> +  //! ycoord contains a vector of the y-coordinates (vertical) of each point
In 3D case, the y coordinate is no longer the vertical - the z coordinate becomes the vertical - this might affect the resulting stress.

2017-05-25 10:57 UTC, kks32 commented on include/GMSH.cc
> +  for (auto const& point : vertices_) {
You can check if the value is maximum here, no need to create a vector of maximum coordinate.

2017-05-25 10:57 UTC, kks32 commented on include/GMSH.cc
> +  double K0 = 0.5;
Naming convention.

2017-05-25 10:57 UTC, kks32 commented on include/GMSH.cc
> +  //! Make two soil parameters for stress calculation
Variable that don't change should be `const`

2017-05-25 20:01 UTC, kks32 commented on include/initStress.h
> +  //! \brief  Make constructor for initial stress
No need for `\brief`

2017-05-25 20:02 UTC, kks32 commented on include/initStress.h
> +  //! To return id_
Remove these two comments. Just say `return id of the point`

2017-05-25 20:02 UTC, kks32 commented on include/initStress.h
> +  std::array<double, 6> stress() const { return stress_; }
Move this to `Point` class

2017-05-25 20:02 UTC, kks32 commented on include/initStress.h
> +  std::array<double, 6> stress() const { return stress_; }
Don't use magic numbers. What's 6?

2017-05-25 20:03 UTC, kks32 commented on include/GMSH.cc
>    if (stresscheck.is_open()) {
This part of the function should be in the IO class.

2017-05-26 02:01 UTC, ezrayst commented on include/GMSH.cc
> +  //! ycoord contains a vector of the y-coordinates (vertical) of each point
Ow, that's really interesting. I though y is always vertical? Then we need if function here

2017-05-26 02:01 UTC, ezrayst commented on include/initStress.h
> +  std::array<double, 6> stress() const { return stress_; }
I thought there are 6 Voigt stresses --> sigxx, sigyy, sigzz, tauyz, tauzx, tauxy? No? It is always 6 right?

2017-05-26 02:12 UTC, ezrayst commented on include/GMSH.cc
> +  for (auto const& point : vertices_) {
regarding the issue of making them in class `point`, I think it's difficult to get the maximum value of the vertical coordinate right? stress is that maximum minus the point right now multiply by a factor.

For this reason I prefer to have a separate class for `initstress`.

2017-05-26 09:20 UTC, kks32 commented on include/GMSH.cc
> +  for (auto const& point : vertices_) {
Line # 93 can happen within # 99.

2017-05-26 09:24 UTC, cw646 commented on include/GMSH.cc
> +  //! ycoord contains a vector of the y-coordinates (vertical) of each point
Yeah, i thought that too. Made for an interesting slump test where the whole cone was moving - if you scroll up in the slack chat you might see it! Gravity is applied in y direction in 2D and z Direction in 3D.

2017-05-26 14:53 UTC, kks32 commented on include/initStress.h
> +  std::array<double, 6> stress() const { return stress_; }
What about 2D? and when I say don't use magic numbers, it is to say define `const unsigned nstress_components = 6` or something like that.

2017-06-16 10:48 UTC, closed without merging